### ISSUE TITLE
NuGet package for OC 1.0?

### ISSUE THREAD

**Issue by devlife** [Lombiq/Helpful-Extensions#34]
Is there a NuGet package for OC 1.0?

**Comment by Piedone** [comment]
Not yet but we're working on it. Stay tuned!

**Comment by Piedone** [comment]
Work on this is tracked here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/23

**Comment by Piedone** [comment]
We've published a preview NuGet package: https://www.nuget.org/packages/Lombiq.HelpfulExtensions/ Could you check, please?

**Comment by devlife** [comment]
Yes. I just started a new project and will start this today.

**Comment by devlife** [comment]
@Piedone I removed my submodules and added the Nuget package but I no longer see the features available.

**Comment by Piedone** [comment]
Hmm, it really should work. Do you have any errors in the log? Also, note that our packages require Orchard 1.2.1 or later.

**Comment by devlife** [comment]
Hmm odd. I must have mucked something up while removing the submodules but I think it looks good now!

**Comment by Piedone** [comment]
Great then!

Note that we're still working on NuGet publishing. We'll have proper releases, and most of our projects will have a version number of at least 1.0 since most of them have long been production-ready. So, things may change but it's pretty certain that the `Lombiq.HelpfulExtensions` package will remain (and you'll notice updates).

**Comment by Piedone** [comment]
Let me keep this open until the corresponding PR is merged.

**Comment by devlife** [comment]
That sounds good. My project will take several months so I've got time to continue testing as new versions become available.
